In [1]:
import numpy as np

from pyboolnet.external.bnet2primes import bnet_text2primes
from pyboolnet.state_transition_graphs import primes2stg

from transition_matrix import get_transition_matrix
from basins import get_strong_basins, expand_strong_basin_matrix, compare_strong_basins

In [2]:
DEBUG = True

np.set_printoptions(linewidth=1000, precision=3, suppress=True)

In [3]:
bnet = """
A, A | B & C
B, B & !C
C, B & !C | !C & !D | !B & C & D
D, !A & !B & !C & !D | !A & C & D
"""

update = "asynchronous"

primes = bnet_text2primes(bnet)
primes = {key: primes[key] for key in sorted(primes)}
stg = primes2stg(primes, update)

transition_matrix = get_transition_matrix(stg, update=update, DEBUG=DEBUG)

print(transition_matrix)

[[0.5  0.25 0.25 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.25 0.75 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.25 0.   0.75 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   1.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.75 0.   0.25 0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.25 0.5  0.   0.25 0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.25 0.   0.25 0.   0.25 0.   0.   0.   0.   0.   0.   0.   0.25 0.  ]
 [0.   0.   0.   0.25 0.   0.25 0.   0.25 0.   0.   0.   0.   0.   0.   0.   0.25]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.75 0.   0.25 0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.25 0.75 0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.25 0.   0.75 0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.25 0.75 0.   0.   0.   0.  ]
 [0.

In [4]:
strong_basin = get_strong_basins(transition_matrix, DEBUG=DEBUG)

print(strong_basin)

[[ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]]


In [5]:
from matrix_operations import compress_matrix
from grouping import sd_grouping

sd_indexes = sd_grouping(bnet, DEBUG=DEBUG)

print(sd_indexes)

Tm = compress_matrix(transition_matrix, sd_indexes, DEBUG=DEBUG)

print("Tm")
print(np.round(Tm, 3))


[[4, 5, 6, 7], [], [0, 1, 2], [3], [12, 14], [8, 10], [13, 15], [9, 11]]
Tm
[[0.75  0.062 0.062 0.062 0.    0.062 0.   ]
 [0.    1.    0.    0.    0.    0.    0.   ]
 [0.    0.    1.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.875 0.125 0.    0.   ]
 [0.    0.    0.    0.    1.    0.    0.   ]
 [0.    0.    0.    0.25  0.    0.625 0.125]
 [0.    0.    0.    0.    0.25  0.    0.75 ]]


In [6]:
sd_strong_basin = get_strong_basins(Tm, DEBUG=DEBUG)

print(sd_strong_basin)

[[-1.]
 [ 0.]
 [ 1.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]]


In [7]:
sd_strong_basin_expanded = expand_strong_basin_matrix(
    sd_strong_basin, sd_indexes, DEBUG=DEBUG
)

print(sd_strong_basin_expanded.__repr__())

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.]])


In [8]:
compare_strong_basins(strong_basin, sd_strong_basin_expanded, DEBUG=DEBUG)

(np.int64(12), np.int64(0), np.int64(4), np.int64(0))