In [1]:
import numpy as np

from pyboolnet.external.bnet2primes import bnet_text2primes
from pyboolnet.state_transition_graphs import primes2stg

from basins import get_node_average_values
from transition_matrix import get_transition_matrix, get_uniform_matrix
from matrix_operations import nsquare, compress_matrix, expand_matrix, get_rms_diff, get_dkl
from grouping import sd_grouping, null_grouping

np.set_printoptions(linewidth=1000, precision=3, suppress=True)

In [2]:
bnet = """
A, A | B & C
B, B & !C
C, B & !C | !C & !D | !B & C & D
D, !A & !B & !C & !D | !A & C & D
"""

update = "asynchronous"

DEBUG = True

In [3]:
primes = bnet_text2primes(bnet)
primes = {key: primes[key] for key in sorted(primes)}
stg = primes2stg(primes, update)

In [4]:
T = get_transition_matrix(stg, update=update, DEBUG=DEBUG)
T_inf = nsquare(T, 20, DEBUG=DEBUG)

print("T_inf")
print(T_inf)

T_inf
[[0.333 0.333 0.333 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.333 0.333 0.333 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.333 0.333 0.333 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    1.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.167 0.167 0.167 0.    0.    0.    0.    0.    0.25  0.    0.25  0.    0.    0.    0.    0.   ]
 [0.1   0.1   0.1   0.2   0.    0.    0.    0.    0.25  0.    0.25  0.    0.    0.    0.    0.   ]
 [0.167 0.167 0.167 0.    0.    0.    0.    0.    0.25  0.    0.25  0.    0.    0.    0.    0.   ]
 [0.033 0.033 0.033 0.4   0.    0.    0.    0.    0.25  0.    0.25  0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.5   0.    0.5   0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.5   0.    0.5   0.    0.    0.    0.    0.   ]
 [0.

In [5]:
sd_indices = sd_grouping(bnet, DEBUG=DEBUG)
Tsd = compress_matrix(T, sd_indices, DEBUG=DEBUG)
Tsd_inf = nsquare(Tsd, 20, DEBUG=DEBUG)
Tsd_inf_expanded = expand_matrix(Tsd_inf, sd_indices, DEBUG=DEBUG)

print("Tsd_inf_expanded")
print(Tsd_inf_expanded)

Tsd_inf_expanded
[[0.333 0.333 0.333 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.333 0.333 0.333 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.333 0.333 0.333 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    1.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.083 0.083 0.083 0.25  0.    0.    0.    0.    0.25  0.    0.25  0.    0.    0.    0.    0.   ]
 [0.083 0.083 0.083 0.25  0.    0.    0.    0.    0.25  0.    0.25  0.    0.    0.    0.    0.   ]
 [0.083 0.083 0.083 0.25  0.    0.    0.    0.    0.25  0.    0.25  0.    0.    0.    0.    0.   ]
 [0.083 0.083 0.083 0.25  0.    0.    0.    0.    0.25  0.    0.25  0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.5   0.    0.5   0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.5   0.    0.5   0.    0.    0.    0.    

In [6]:
null_indices = null_grouping(bnet, DEBUG=DEBUG)
Tnull = compress_matrix(T, null_indices, DEBUG=DEBUG)
Tnull_inf = nsquare(Tnull, 20, DEBUG=DEBUG)
Tnull_inf_expanded = expand_matrix(Tnull_inf, null_indices, DEBUG=DEBUG)

print("Tnull_inf_expanded")
print(Tnull_inf_expanded)

Tnull_inf_expanded
[[0.    0.    0.    0.25  0.    0.    0.    0.    0.375 0.    0.375 0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.25  0.    0.    0.    0.    0.375 0.    0.375 0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.25  0.    0.    0.    0.    0.375 0.    0.375 0.    0.    0.    0.    0.   ]
 [0.    0.    0.    1.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.25  0.    0.    0.    0.    0.375 0.    0.375 0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.25  0.    0.    0.    0.    0.375 0.    0.375 0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.25  0.    0.    0.    0.    0.375 0.    0.375 0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.25  0.    0.    0.    0.    0.375 0.    0.375 0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.5   0.    0.5   0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.25  0.    0.    0.    0.    0.375 0.    0.375 0.    0.    0.    0.  

In [7]:
Tref = get_uniform_matrix(2**(len(primes)))

print("Tref")
print(Tref)

Tref
[[0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062]
 [0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062]
 [0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062]
 [0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062]
 [0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062]
 [0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062]
 [0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062]
 [0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062]
 [0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062]
 [0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062]
 [0.0

In [8]:
T_node_average_values = get_node_average_values(T_inf, DEBUG=DEBUG)
Tsd_node_average_values = get_node_average_values(Tsd_inf_expanded, DEBUG=DEBUG)
Tnull_node_average_values = get_node_average_values(Tnull_inf_expanded, DEBUG=DEBUG)
ref_node_average_values = get_node_average_values(Tref, DEBUG=DEBUG)

print("T_node_average_values")
print(T_node_average_values)

print("Tsd_node_average_values")
print(Tsd_node_average_values)

print("Tnull_node_average_values")
print(Tnull_node_average_values)

print("ref_node_average_values")
print(ref_node_average_values)

T_node_average_values
[[0.625 0.    0.504 0.192]]
Tsd_node_average_values
[[0.625 0.    0.521 0.208]]
Tnull_node_average_values
[[0.734 0.    0.633 0.266]]
ref_node_average_values
[[0.5 0.5 0.5 0.5]]


In [9]:
sd_rmsd = get_rms_diff(T_node_average_values, Tsd_node_average_values, partial=True, DEBUG=DEBUG)
null_rmsd = get_rms_diff(T_node_average_values, Tnull_node_average_values, partial=True, DEBUG=DEBUG)
ref_rmsd = get_rms_diff(T_node_average_values, ref_node_average_values, partial=True, DEBUG=DEBUG)

print(f"RMSD between STG and SD average node values: {sd_rmsd}")
print(f"RMSD between STG and null average node values: {null_rmsd}")
print(f"RMSD between STG and reference average node values: {ref_rmsd}")

RMSD between STG and SD average node values: 0.01178511301977576
RMSD between STG and null average node values: 0.09217168237651983
RMSD between STG and reference average node values: 0.30029643918782806
