In [1]:
import numpy as np
import networkx as nx

from pyboolnet.external.bnet2primes import bnet_text2primes
from pyboolnet.state_transition_graphs import primes2stg

from transition_matrix import get_transition_matrix
from transition_matrix import get_markov_chain
from matrix_operations import compress_matrix
from grouping import sd_grouping
from paths import get_all_paths, get_markov_chain_path_probs

np.set_printoptions(linewidth=1000, precision=3, suppress=True)

In [2]:
bnet = """
A, A | B & C
B, B & !C
C, B & !C | !C & !D | !B & C & D
D, !A & !B & !C & !D | !A & C & D
"""

update = "asynchronous"

DEBUG = True

In [3]:
primes = bnet_text2primes(bnet)
primes = {key: primes[key] for key in sorted(primes)}
stg = primes2stg(primes, update)

T = get_transition_matrix(stg, update=update, DEBUG=DEBUG)

print("T")
print(np.round(T, 3))

T
[[0.5  0.25 0.25 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.25 0.75 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.25 0.   0.75 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   1.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.75 0.   0.25 0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.25 0.5  0.   0.25 0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.25 0.   0.25 0.   0.25 0.   0.   0.   0.   0.   0.   0.   0.25 0.  ]
 [0.   0.   0.   0.25 0.   0.25 0.   0.25 0.   0.   0.   0.   0.   0.   0.   0.25]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.75 0.   0.25 0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.25 0.75 0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.25 0.   0.75 0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.25 0.75 0.   0.   0.   0.  ]
 [

In [ ]:


sd_indices = sd_grouping(bnet, DEBUG=DEBUG)

print(sd_indices)

Tm = compress_matrix(T, sd_indices, DEBUG=DEBUG)

print("Tm")
print(np.round(Tm, 3))

print(Tm.__repr__())

[[4, 5, 6, 7], [], [0, 1, 2], [3], [12, 14], [8, 10], [13, 15], [9, 11]]
Tm
[[0.75  0.062 0.062 0.062 0.    0.062 0.   ]
 [0.    1.    0.    0.    0.    0.    0.   ]
 [0.    0.    1.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.875 0.125 0.    0.   ]
 [0.    0.    0.    0.    1.    0.    0.   ]
 [0.    0.    0.    0.25  0.    0.625 0.125]
 [0.    0.    0.    0.    0.25  0.    0.75 ]]
array([[0.75 , 0.062, 0.062, 0.062, 0.   , 0.062, 0.   ],
       [0.   , 1.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 1.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.875, 0.125, 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 1.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.25 , 0.   , 0.625, 0.125],
       [0.   , 0.   , 0.   , 0.   , 0.25 , 0.   , 0.75 ]])


In [ ]:

markov_chain = get_markov_chain(Tm, sd_indices, DEBUG=DEBUG)

print(markov_chain.edges())
print(len(markov_chain.edges()))
print(markov_chain.edges(data=True))


[('0', '0'), ('0', '2'), ('0', '3'), ('0', '4'), ('0', '6'), ('2', '2'), ('3', '3'), ('4', '4'), ('4', '5'), ('6', '4'), ('6', '6'), ('6', '7'), ('5', '5'), ('7', '5'), ('7', '7')]
15
[('0', '0', {'weight': np.float64(0.75)}), ('0', '2', {'weight': np.float64(0.0625)}), ('0', '3', {'weight': np.float64(0.0625)}), ('0', '4', {'weight': np.float64(0.0625)}), ('0', '6', {'weight': np.float64(0.0625)}), ('2', '2', {'weight': np.float64(1.0)}), ('3', '3', {'weight': np.float64(1.0)}), ('4', '4', {'weight': np.float64(0.875)}), ('4', '5', {'weight': np.float64(0.125)}), ('6', '4', {'weight': np.float64(0.25)}), ('6', '6', {'weight': np.float64(0.625)}), ('6', '7', {'weight': np.float64(0.125)}), ('5', '5', {'weight': np.float64(1.0)}), ('7', '5', {'weight': np.float64(0.25)}), ('7', '7', {'weight': np.float64(0.75)})]


In [6]:
all_paths = get_all_paths(markov_chain, DEBUG=DEBUG)

print(len(all_paths))
print(all_paths)

15
[('0', '2'), ('0', '3'), ('0', '4'), ('0', '6'), ('4', '5'), ('6', '4'), ('6', '7'), ('7', '5'), ('0', '4', '5'), ('0', '6', '4'), ('0', '6', '7'), ('6', '4', '5'), ('6', '7', '5'), ('0', '6', '4', '5'), ('0', '6', '7', '5')]


In [7]:
markov_chain_path_probs = get_markov_chain_path_probs(markov_chain, all_paths, DEBUG=DEBUG)

print(markov_chain_path_probs)

{('0', '2'): np.float64(0.25), ('0', '3'): np.float64(0.25), ('0', '4'): np.float64(0.25), ('0', '6'): np.float64(0.25), ('4', '5'): np.float64(1.0), ('6', '4'): np.float64(0.6666666666666666), ('6', '7'): np.float64(0.3333333333333333), ('7', '5'): np.float64(1.0), ('0', '4', '5'): np.float64(0.25), ('0', '6', '4'): np.float64(0.16666666666666666), ('0', '6', '7'): np.float64(0.08333333333333333), ('6', '4', '5'): np.float64(0.6666666666666666), ('6', '7', '5'): np.float64(0.3333333333333333), ('0', '6', '4', '5'): np.float64(0.16666666666666666), ('0', '6', '7', '5'): np.float64(0.08333333333333333)}


In [ ]:
from paths import get_stg_path_probs

stg_path_probs = get_stg_path_probs(all_paths, sd_indices, stg, T, DEBUG=DEBUG)

In [9]:
print(markov_chain_path_probs)
print(stg_path_probs)

{('0', '2'): np.float64(0.25), ('0', '3'): np.float64(0.25), ('0', '4'): np.float64(0.25), ('0', '6'): np.float64(0.25), ('4', '5'): np.float64(1.0), ('6', '4'): np.float64(0.6666666666666666), ('6', '7'): np.float64(0.3333333333333333), ('7', '5'): np.float64(1.0), ('0', '4', '5'): np.float64(0.25), ('0', '6', '4'): np.float64(0.16666666666666666), ('0', '6', '7'): np.float64(0.08333333333333333), ('6', '4', '5'): np.float64(0.6666666666666666), ('6', '7', '5'): np.float64(0.3333333333333333), ('0', '6', '4', '5'): np.float64(0.16666666666666666), ('0', '6', '7', '5'): np.float64(0.08333333333333333)}
{('0', '2'): np.float64(0.35000000000000003), ('0', '3'): np.float64(0.14999999999999988), ('0', '4'): np.float64(0.3500000000000001), ('0', '6'): np.float64(0.14999999999999988), ('4', '5'): np.float64(0.9999999999999996), ('6', '4'): np.float64(0.6999999999999997), ('6', '7'): np.float64(0.29999999999999993), ('7', '5'): np.float64(1.0), ('0', '4', '5'): np.float64(0.35), ('0', '6', '4

In [10]:
from paths import compare_path_reachability

TP, FP, TN, FN = compare_path_reachability(stg_path_probs, markov_chain_path_probs, DEBUG=DEBUG)
print("TP, FP, TN, FN for all paths")
print(TP, FP, TN, FN)

TP, FP, TN, FN = compare_path_reachability(stg_path_probs, markov_chain_path_probs, "edges", DEBUG=DEBUG)
print("TP, FP, TN, FN for edges")
print(TP, FP, TN, FN)

TP, FP, TN, FN = compare_path_reachability(stg_path_probs, markov_chain_path_probs, "non_edges", DEBUG=DEBUG)
print("TP, FP, TN, FN for non_edges")
print(TP, FP, TN, FN)

TP, FP, TN, FN = compare_path_reachability(stg_path_probs, markov_chain_path_probs, "path_2", DEBUG=DEBUG)
print("TP, FP, TN, FN for path_2")
print(TP, FP, TN, FN)

TP, FP, TN, FN = compare_path_reachability(stg_path_probs, markov_chain_path_probs, "path_3", DEBUG=DEBUG)
print("TP, FP, TN, FN for path_3")
print(TP, FP, TN, FN)

TP, FP, TN, FN = compare_path_reachability(stg_path_probs, markov_chain_path_probs, "path_4", DEBUG=DEBUG)
print("TP, FP, TN, FN for path_4")
print(TP, FP, TN, FN)

TP, FP, TN, FN for all paths
15 0 0 0
TP, FP, TN, FN for edges
8 0 0 0
TP, FP, TN, FN for non_edges
7 0 0 0
TP, FP, TN, FN for path_2
5 0 0 0
TP, FP, TN, FN for path_3
2 0 0 0
TP, FP, TN, FN for path_4
0 0 0 0


In [11]:
from paths import compare_path_rmsd

rmsd = compare_path_rmsd(stg_path_probs, markov_chain_path_probs, DEBUG=DEBUG)
print("rmsd for all paths")
print(rmsd)

rmsd = compare_path_rmsd(stg_path_probs, markov_chain_path_probs, "edges", DEBUG=DEBUG)
print("rmsd for edges")
print(rmsd)

rmsd = compare_path_rmsd(stg_path_probs, markov_chain_path_probs, "non_edges", DEBUG=DEBUG)
print("rmsd for non_edges")
print(rmsd)

rmsd = compare_path_rmsd(stg_path_probs, markov_chain_path_probs, "path_2", DEBUG=DEBUG)
print("rmsd for path_2")
print(rmsd)

rmsd = compare_path_rmsd(stg_path_probs, markov_chain_path_probs, "path_3", DEBUG=DEBUG)
print("rmsd for path_3")
print(rmsd)

rmsd = compare_path_rmsd(stg_path_probs, markov_chain_path_probs, "path_4", DEBUG=DEBUG)
print("rmsd for path_4")
print(rmsd)

rmsd for all paths
0.0669770552198731
rmsd for edges
0.07264831572567794
rmsd for non_edges
0.05984105932344766
rmsd for path_2
0.06106462878695723
rmsd for path_3
0.056666666666666754
rmsd for path_4
0


In [12]:
from paths import get_random_path_probs

rmsd_all = []
rmsd_edges = []
rmsd_non_edges = []
rmsd_path_2 = []
rmsd_path_3 = []
rmsd_path_4 = []

for i in range(100):
    random_path_probs = get_random_path_probs(markov_chain_path_probs, seed=i)

    print("random_path_probs")
    print(random_path_probs)

    rmsd_all.append(compare_path_rmsd(stg_path_probs, random_path_probs, DEBUG=DEBUG))
    rmsd_edges.append(compare_path_rmsd(stg_path_probs, random_path_probs, "edges", DEBUG=DEBUG))
    rmsd_non_edges.append(compare_path_rmsd(stg_path_probs, random_path_probs, "non_edges", DEBUG=DEBUG))
    rmsd_path_2.append(compare_path_rmsd(stg_path_probs, random_path_probs, "path_2", DEBUG=DEBUG))
    rmsd_path_3.append(compare_path_rmsd(stg_path_probs, random_path_probs, "path_3", DEBUG=DEBUG))
    rmsd_path_4.append(compare_path_rmsd(stg_path_probs, random_path_probs, "path_4", DEBUG=DEBUG))

print("rmsd for all paths")
print(np.mean(rmsd_all), np.std(rmsd_all))

print("rmsd for edges")
print(np.mean(rmsd_edges), np.std(rmsd_edges))

print("rmsd for non_edges")
print(np.mean(rmsd_non_edges), np.std(rmsd_non_edges))

print("rmsd for path_2")
print(np.mean(rmsd_path_2), np.std(rmsd_path_2))

print("rmsd for path_3")
print(np.mean(rmsd_path_3), np.std(rmsd_path_3))

print("rmsd for path_4")
print(np.mean(rmsd_path_4), np.std(rmsd_path_4))

random_path_probs
{('0', '2'): 0.3700578276458176, ('0', '3'): 0.3321644972830869, ('0', '4'): 0.18431049041512548, ('0', '6'): 0.1134671846559699, ('4', '5'): 1.0, ('6', '4'): 0.34064355126127693, ('6', '7'): 0.659356448738723, ('7', '5'): 1.0, ('0', '4', '5'): 0.18431049041512548, ('0', '6', '4'): 0.03865186473282866, ('0', '6', '7'): 0.07481531992314124, ('6', '4', '5'): 0.34064355126127693, ('6', '7', '5'): 0.659356448738723, ('0', '6', '4', '5'): 0.03865186473282866, ('0', '6', '7', '5'): 0.07481531992314124}
random_path_probs
{('0', '2'): 0.06716057607817613, ('0', '3'): 0.4235809782338752, ('0', '4'): 0.3817648344112146, ('0', '6'): 0.12749361127673414, ('4', '5'): 1.0, ('6', '4'): 0.4082259386891194, ('6', '7'): 0.5917740613108805, ('7', '5'): 1.0, ('0', '4', '5'): 0.3817648344112146, ('0', '6', '4'): 0.052046199140310494, ('0', '6', '7'): 0.07544741213642364, ('6', '4', '5'): 0.4082259386891194, ('6', '7', '5'): 0.5917740613108805, ('0', '6', '4', '5'): 0.052046199140310494, (