In [1]:
import numpy as np

from pyboolnet.external.bnet2primes import bnet_text2primes
from pyboolnet.state_transition_graphs import primes2stg

from transition_matrix import get_transition_matrix
from decisions import get_decision_matrix

In [2]:
DEBUG = True

np.set_printoptions(linewidth=1000, precision=3, suppress=True)

In [3]:
# bnet = """
# A, A | B & C
# B, B & !C
# C, B & !C | !C & !D | !B & C & D
# D, !A & !B & !C & !D | !A & C & D
# """

bnet = 'A, !A'

update = "asynchronous"
# update = "synchronous"

primes = bnet_text2primes(bnet)
primes = {key: primes[key] for key in sorted(primes)}
stg = primes2stg(primes, update)

transition_matrix = get_transition_matrix(stg, update=update, DEBUG=DEBUG)

print(transition_matrix)

[[0. 1.]
 [1. 0.]]


In [4]:
decision_matrix = get_decision_matrix(transition_matrix, DEBUG=DEBUG)
print(decision_matrix)

T_inf: [[1. 0.]
 [0. 1.]]
attractor_indexes: [[0, 1]]
attractor: [0, 1]
index: 0
basin in progress: [[1. 1.]
 [0. 0.]]
reachable 1
attractor: [0, 1]
index: 0
index: 1
basin in progress: [[1. 1.]
 [1. 1.]]
reachable 1
basin: [[1. 1.]
 [1. 1.]]
[[ 0 -1]
 [-1  0]]


In [ ]:
from matrix_operations import compress_matrix
from grouping import sd_grouping

sd_indices = sd_grouping(bnet, DEBUG=DEBUG)

print(sd_indices)

Tm = compress_matrix(transition_matrix, sd_indices, DEBUG=DEBUG)

print("Tm")
print(np.round(Tm, 3))

markov_decision_matrix = get_decision_matrix(Tm)
print(markov_decision_matrix)

[[0, 1]]
Tm
[[1.]]
T_inf: [[1.]]
attractor_indexes: [[0]]
attractor: [0]
index: 0
basin in progress: [[1.]]
reachable 1
basin: [[1.]]
[[-1]]


In [ ]:
from decisions import expand_decision_matrix

expanded_matrix = expand_decision_matrix(markov_decision_matrix, sd_indices, DEBUG=DEBUG)
print(expanded_matrix)

[[-1. -1.]
 [-1. -1.]]


In [7]:
from decisions import compare_decision_matrices

TP, FP, TN, FN = compare_decision_matrices(decision_matrix, expanded_matrix, DEBUG=DEBUG)
print(TP, FP, TN, FN)

0 0 2 0
