In [1]:
import numpy as np

from pyboolnet.external.bnet2primes import bnet_text2primes
from pyboolnet.state_transition_graphs import primes2stg

from transition_matrix import get_transition_matrix
from matrix_operations import nsquare, compress_matrix, expand_matrix, get_rms_diff, get_dkl
from grouping import sd_grouping, null_grouping
from basins import get_convergence_matrix, get_basin_ratios
from attractors import get_predicted_attractors

np.set_printoptions(linewidth=1000, precision=3, suppress=True)

In [2]:
bnet = """
A, A | B & C
B, B & !C
C, B & !C | !C & !D | !B & C & D
D, !A & !B & !C & !D | !A & C & D
"""

update = "asynchronous"

DEBUG = True

In [3]:
primes = bnet_text2primes(bnet)
primes = {key: primes[key] for key in sorted(primes)}
stg = primes2stg(primes, update)

In [4]:
T = get_transition_matrix(stg, update=update, DEBUG=DEBUG)
T_inf = nsquare(T, 20, DEBUG=DEBUG)

print("T_inf")
print(T_inf)

T_inf
[[0.333 0.333 0.333 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.333 0.333 0.333 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.333 0.333 0.333 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    1.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.167 0.167 0.167 0.    0.    0.    0.    0.    0.25  0.    0.25  0.    0.    0.    0.    0.   ]
 [0.1   0.1   0.1   0.2   0.    0.    0.    0.    0.25  0.    0.25  0.    0.    0.    0.    0.   ]
 [0.167 0.167 0.167 0.    0.    0.    0.    0.    0.25  0.    0.25  0.    0.    0.    0.    0.   ]
 [0.033 0.033 0.033 0.4   0.    0.    0.    0.    0.25  0.    0.25  0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.5   0.    0.5   0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.5   0.    0.5   0.    0.    0.    0.    0.   ]
 [0.

In [5]:
sd_indices = sd_grouping(bnet, DEBUG=DEBUG)
Tsd = compress_matrix(T, sd_indices, DEBUG=DEBUG)

predicted_attractor_indices = get_predicted_attractors(Tsd, sd_indices, as_indices=True, DEBUG=DEBUG)

Tsd_inf = nsquare(Tsd, 20, DEBUG=DEBUG)
Tsd_inf_expanded = expand_matrix(Tsd_inf, sd_indices, DEBUG=DEBUG)

print("Tsd_inf_expanded")
print(Tsd_inf_expanded)

Tsd_inf_expanded
[[0.333 0.333 0.333 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.333 0.333 0.333 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.333 0.333 0.333 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    1.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.083 0.083 0.083 0.25  0.    0.    0.    0.    0.25  0.    0.25  0.    0.    0.    0.    0.   ]
 [0.083 0.083 0.083 0.25  0.    0.    0.    0.    0.25  0.    0.25  0.    0.    0.    0.    0.   ]
 [0.083 0.083 0.083 0.25  0.    0.    0.    0.    0.25  0.    0.25  0.    0.    0.    0.    0.   ]
 [0.083 0.083 0.083 0.25  0.    0.    0.    0.    0.25  0.    0.25  0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.5   0.    0.5   0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.5   0.    0.5   0.    0.    0.    0.    

In [6]:
null_indices = null_grouping(bnet, DEBUG=DEBUG)
Tnull = compress_matrix(T, null_indices, DEBUG=DEBUG)
Tnull_inf = nsquare(Tnull, 20, DEBUG=DEBUG)
Tnull_inf_expanded = expand_matrix(Tnull_inf, null_indices, DEBUG=DEBUG)

print("Tnull_inf_expanded")
print(Tnull_inf_expanded)

Tnull_inf_expanded
[[0.    0.    0.    0.25  0.    0.    0.    0.    0.375 0.    0.375 0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.25  0.    0.    0.    0.    0.375 0.    0.375 0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.25  0.    0.    0.    0.    0.375 0.    0.375 0.    0.    0.    0.    0.   ]
 [0.    0.    0.    1.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.25  0.    0.    0.    0.    0.375 0.    0.375 0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.25  0.    0.    0.    0.    0.375 0.    0.375 0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.25  0.    0.    0.    0.    0.375 0.    0.375 0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.25  0.    0.    0.    0.    0.375 0.    0.375 0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.5   0.    0.5   0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.25  0.    0.    0.    0.    0.375 0.    0.375 0.    0.    0.    0.  

In [7]:
T_convergence_matrix = get_convergence_matrix(T_inf, predicted_attractor_indices, DEBUG=DEBUG)
Tsd_convergence_matrix = get_convergence_matrix(Tsd_inf_expanded, predicted_attractor_indices, DEBUG=DEBUG)
Tnull_convergence_matrix = get_convergence_matrix(Tnull_inf_expanded, predicted_attractor_indices, DEBUG=DEBUG)

T_basin_ratios = get_basin_ratios(T_convergence_matrix, DEBUG=DEBUG)
Tsd_basin_ratios = get_basin_ratios(Tsd_convergence_matrix, DEBUG=DEBUG)
Tnull_basin_ratios = get_basin_ratios(Tnull_convergence_matrix, DEBUG=DEBUG)

print("T_basin_ratios")
print(T_basin_ratios)

print("Tsd_basin_ratios")
print(Tsd_basin_ratios)

print("Tnull_basin_ratios")
print(Tnull_basin_ratios)

T_basin_ratios
[[0.275 0.1   0.625]]
Tsd_basin_ratios
[[0.25  0.125 0.625]]
Tnull_basin_ratios
[[0.    0.266 0.734]]


In [8]:
sd_rmsd = get_rms_diff(T_basin_ratios, Tsd_basin_ratios, partial=True, DEBUG=DEBUG)
sd_dkl = get_dkl(T_basin_ratios, Tsd_basin_ratios, partial=True, DEBUG=DEBUG)

null_rmsd = get_rms_diff(T_basin_ratios, Tnull_basin_ratios, partial=True, DEBUG=DEBUG)
null_dkl = get_dkl(T_basin_ratios, Tnull_basin_ratios, partial=True, DEBUG=DEBUG)

print(f"RMSD between STG and SD attractor ratios: {sd_rmsd}")
print(f"DKL between STG and SD attractor ratios: {sd_dkl}")

print(f"RMSD between STG and null attractor ratios: {null_rmsd}")
print(f"DKL between STG and null attractor ratios: {null_dkl}")

RMSD between STG and SD attractor ratios: 0.020412414523193142
DKL between STG and SD attractor ratios: 0.0038959443147683175
RMSD between STG and null attractor ratios: 0.19580562747275676
DKL between STG and null attractor ratios: inf


/home/kyuhyongpark/SDMarkov/sdmarkov/matrix_operations.py:401: RuntimeWarning: divide by zero encountered in divide
  ratio = np.divide(A,B, out=np.zeros_like(A, dtype=float), where=A!=0.0)


In [9]:
# all_attractor_states = []
# for attractor in attractor_indices:
#     all_attractor_states.extend(attractor)

# print(all_attractor_states)

# STG_average_node_values = np.zeros(len(primes))
# SD_average_node_values = np.zeros(len(primes))
# for state in all_attractor_states:

#     # convert decimal index to binary string
#     state_str = bin(state)[2:].zfill(len(primes))

#     node_values = np.array([float(state_str[i]) for i in range(len(state_str))])

#     print(f"Node values for state {state}: {node_values}")

#     STG_average_node_values += node_values * STG_state_prob[state]
#     SD_average_node_values += node_values * SD_state_prob[state]

# print(f"STG Average node values: {STG_average_node_values}")
# print(f"SD Average node values: {SD_average_node_values}")

# rmsd = np.sqrt(np.mean((STG_average_node_values - SD_average_node_values)**2))

# print(f"RMSD between STG and SD average node values: {rmsd}")