In [1]:
import numpy as np

from pyboolnet.external.bnet2primes import bnet_text2primes
from pyboolnet.state_transition_graphs import primes2stg

from scc_dags import get_scc_dag, get_attractor_states
from transition_matrix import get_transition_matrix, get_uniform_matrix
from matrix_operations import nsquare, compress_matrix, expand_matrix, get_confusion_matrix
from grouping import sd_grouping, null_grouping
from attractors import attractor_or_transient

np.set_printoptions(linewidth=1000, precision=3, suppress=True)

In [2]:
bnet = """
A, A | B & C
B, B & !C
C, B & !C | !C & !D | !B & C & D
D, !A & !B & !C & !D | !A & C & D
"""

update = "asynchronous"

DEBUG = True

In [3]:
primes = bnet_text2primes(bnet)
primes = {key: primes[key] for key in sorted(primes)}
stg = primes2stg(primes, update)

scc_dag = get_scc_dag(stg)
attractor_indices = get_attractor_states(scc_dag, as_indices=True, DEBUG=DEBUG)

print(attractor_indices)

[[0, 1, 2], [3], [8, 10]]


In [4]:
T = get_transition_matrix(stg, update=update, DEBUG=DEBUG)
T_inf = nsquare(T, 20, DEBUG=DEBUG)

print("T_inf")
print(T_inf)

T_inf
[[0.333 0.333 0.333 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.333 0.333 0.333 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.333 0.333 0.333 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    1.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.167 0.167 0.167 0.    0.    0.    0.    0.    0.25  0.    0.25  0.    0.    0.    0.    0.   ]
 [0.1   0.1   0.1   0.2   0.    0.    0.    0.    0.25  0.    0.25  0.    0.    0.    0.    0.   ]
 [0.167 0.167 0.167 0.    0.    0.    0.    0.    0.25  0.    0.25  0.    0.    0.    0.    0.   ]
 [0.033 0.033 0.033 0.4   0.    0.    0.    0.    0.25  0.    0.25  0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.5   0.    0.5   0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.5   0.    0.5   0.    0.    0.    0.    0.   ]
 [0.

In [5]:
sd_indices = sd_grouping(bnet, DEBUG=DEBUG)
Tsd = compress_matrix(T, sd_indices, DEBUG=DEBUG)
Tsd_inf = nsquare(Tsd, 20, DEBUG=DEBUG)
Tsd_inf_expanded = expand_matrix(Tsd_inf, sd_indices, DEBUG=DEBUG)

print("Tsd_inf_expanded")
print(Tsd_inf_expanded)

Tsd_inf_expanded
[[0.333 0.333 0.333 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.333 0.333 0.333 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.333 0.333 0.333 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    1.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.083 0.083 0.083 0.25  0.    0.    0.    0.    0.25  0.    0.25  0.    0.    0.    0.    0.   ]
 [0.083 0.083 0.083 0.25  0.    0.    0.    0.    0.25  0.    0.25  0.    0.    0.    0.    0.   ]
 [0.083 0.083 0.083 0.25  0.    0.    0.    0.    0.25  0.    0.25  0.    0.    0.    0.    0.   ]
 [0.083 0.083 0.083 0.25  0.    0.    0.    0.    0.25  0.    0.25  0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.5   0.    0.5   0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.5   0.    0.5   0.    0.    0.    0.    

In [6]:
null_indices = null_grouping(bnet, DEBUG=DEBUG)
Tnull = compress_matrix(T, null_indices, DEBUG=DEBUG)
Tnull_inf = nsquare(Tnull, 20, DEBUG=DEBUG)
Tnull_inf_expanded = expand_matrix(Tnull_inf, null_indices, DEBUG=DEBUG)

print("Tnull_inf_expanded")
print(Tnull_inf_expanded)

Tnull_inf_expanded
[[0.    0.    0.    0.25  0.    0.    0.    0.    0.375 0.    0.375 0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.25  0.    0.    0.    0.    0.375 0.    0.375 0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.25  0.    0.    0.    0.    0.375 0.    0.375 0.    0.    0.    0.    0.   ]
 [0.    0.    0.    1.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.25  0.    0.    0.    0.    0.375 0.    0.375 0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.25  0.    0.    0.    0.    0.375 0.    0.375 0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.25  0.    0.    0.    0.    0.375 0.    0.375 0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.25  0.    0.    0.    0.    0.375 0.    0.375 0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.5   0.    0.5   0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.25  0.    0.    0.    0.    0.375 0.    0.375 0.    0.    0.    0.  

In [7]:
Tuniform = get_uniform_matrix(2**(len(primes)))

print("Tuniform")
print(Tuniform)

Tuniform
[[0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062]
 [0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062]
 [0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062]
 [0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062]
 [0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062]
 [0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062]
 [0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062]
 [0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062]
 [0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062]
 [0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062 0.062]
 

In [8]:
STG_attractor_matrix = attractor_or_transient(T_inf)
SD_attractor_matrix = attractor_or_transient(Tsd_inf_expanded)
null_attractor_matrix = attractor_or_transient(Tnull_inf_expanded)
uniform_attractor_matrix = attractor_or_transient(Tuniform)

# print(STG_attractor_matrix)
# print(SD_attractor_matrix)
# print(null_attractor_matrix)
# print(uniform_attractor_matrix)

TP, FP, TN, FN = get_confusion_matrix(STG_attractor_matrix, SD_attractor_matrix, partial=True, DEBUG=DEBUG)

print(TP, FP, TN, FN)

TP, FP, TN, FN = get_confusion_matrix(STG_attractor_matrix, null_attractor_matrix, partial=True, DEBUG=DEBUG)

print(TP, FP, TN, FN)

TP, FP, TN, FN = get_confusion_matrix(STG_attractor_matrix, uniform_attractor_matrix, partial=True, DEBUG=DEBUG)

print(TP, FP, TN, FN)

6 0 10 0
3 0 10 3
6 10 0 0
