Get succession diagram nodes, their states, and the corresponding indices

In [1]:
from succession_diagram import get_sd_nodes
from succession_diagram import get_SD_node_states
from succession_diagram import states_to_indexes


bnet = """
A, A | B & C
B, B & !C
C, B & !C | !C & !D | !B & C & D
D, !A & !B & !C & !D | !A & C & D
"""

nodes, sd_nodes = get_sd_nodes(bnet)

print(nodes)
print(sd_nodes)

sd_node_states = get_SD_node_states(nodes, sd_nodes)

print(sd_node_states)

indexes = states_to_indexes(sd_node_states)

print(indexes)

['A', 'B', 'C', 'D']
[{}, {'B': 0}, {'A': 0, 'B': 0}, {'A': 0, 'B': 0, 'C': 1, 'D': 1}, {'A': 1, 'D': 0}, {'A': 1, 'B': 0, 'D': 0}]
[['0100', '0101', '0110', '0111', '1101', '1111'], ['1001', '1011'], ['0000', '0001', '0010'], ['0011'], ['1100', '1110'], ['1000', '1010']]
[[4, 5, 6, 7, 13, 15], [9, 11], [0, 1, 2], [3], [12, 14], [8, 10]]


domRec ignored: No domain atoms found.
domRec ignored: No domain atoms found.


Get the STG of the model, and its transition matrix.

In [2]:
import numpy as np

from pyboolnet.external.bnet2primes import bnet_text2primes
from pyboolnet.state_transition_graphs import primes2stg

from transition_matrix import get_transition_matrix

primes = bnet_text2primes(bnet)
update = "asynchronous"
stg = primes2stg(primes, update)

T = get_transition_matrix(stg)

np.set_printoptions(linewidth=1000, precision=2)

print(T)

[[0.5  0.25 0.25 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.25 0.75 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.25 0.   0.75 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   1.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.75 0.   0.25 0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.25 0.5  0.   0.25 0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.25 0.   0.25 0.   0.25 0.   0.   0.   0.   0.   0.   0.   0.25 0.  ]
 [0.   0.   0.   0.25 0.   0.25 0.   0.25 0.   0.   0.   0.   0.   0.   0.   0.25]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.75 0.   0.25 0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.25 0.75 0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.25 0.   0.75 0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.25 0.75 0.   0.   0.   0.  ]
 [0.

Get the transition matrix of metastates.

Get other reference matrices

In [3]:
from transition_matrix import get_identity_matrix
from transition_matrix import get_uniform_matrix

N = len(nodes)

I = get_identity_matrix(N)
U = get_uniform_matrix(N)

print(I)
print(U)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]]
